"""Testando correção em models de atleta UUID

Revision ID: 13e381cd2cc2
Revises: 9d62b730fdca
Create Date: 2025-01-22 19:47:11.066555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e381cd2cc2'
down_revision: Union[str, None] = '9d62b730fdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
