"""Corrigindo endereco na tabela CT

Revision ID: 35e29956e90d
Revises: 63791eb31062
Create Date: 2025-01-22 18:26:46.428367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e29956e90d'
down_revision: Union[str, None] = '63791eb31062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('endereco', sa.String(length=60), nullable=False))
    op.drop_column('centros_treinamento', 'endereço')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('endereço', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('centros_treinamento', 'endereco')
    # ### end Alembic commands ###
