"""Corrigindo outro erro na tabela Atleta

Revision ID: 4a2efc3d1fc5
Revises: c5bd1421bf00
Create Date: 2025-01-22 19:28:05.475073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2efc3d1fc5'
down_revision: Union[str, None] = 'c5bd1421bf00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('peso', sa.Float(), nullable=False))
    op.alter_column('atletas', 'idade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletas', 'idade',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('atletas', 'peso')
    # ### end Alembic commands ###
