"""Testando correção em models de atleta

Revision ID: 9d62b730fdca
Revises: 4a2efc3d1fc5
Create Date: 2025-01-22 19:44:05.989490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d62b730fdca'
down_revision: Union[str, None] = '4a2efc3d1fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
