"""Corrigindo erro na tabela atleta

Revision ID: c5bd1421bf00
Revises: 35e29956e90d
Create Date: 2025-01-22 19:26:12.734258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5bd1421bf00'
down_revision: Union[str, None] = '35e29956e90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('atletas', 'creted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('creted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('atletas', 'created_at')
    # ### end Alembic commands ###
