"""CCCCC

Revision ID: f4a64a08a483
Revises: e652f8503b00
Create Date: 2025-01-22 19:58:54.630927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a64a08a483'
down_revision: Union[str, None] = 'e652f8503b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('atletas_categoria_id_fkey', 'atletas', type_='foreignkey')
    op.drop_column('atletas', 'categoria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('atletas_categoria_id_fkey', 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    # ### end Alembic commands ###
